name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 18 * * 0"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: komar0ff
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_padding: 0%
          config_timezone: Asia/Tokyo
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: icons    # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 8
          plugin_reactions: yes
          plugin_reactions_limit: 200                  # Compute reactions over last 200 issue comments
          plugin_reactions_limit_issues: 100           # Compute reactions over last 100 issues/pull requests opened
          plugin_reactions_limit_discussions: 100      # Compute reactions over last 100 discussions
          plugin_reactions_limit_discussions_comments: 100 # Compute reactions over last 100 discussions comments
          plugin_reactions_days: 14                    # Compute reactions on issue comments posted less than 14 days ago
          plugin_reactions_display: absolute           # Display percentages based on the total amoun fetched
          plugin_reactions_details: count, percentage  # Display reactions count and percentage
          plugin_reactions_ignored: bot                # Ignore "bot" user
