name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 18 * * 0"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: komar0ff
          template: classic
          base: header, activity, repositories
          config_display: large
          config_padding: 0%
          config_timezone: Europe/Moscow
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: icons    # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_ignored: html, css, makefile
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%
          plugin_languages_details: percentage
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_limit_issues: 100
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_days: 14
          plugin_reactions_display: absolute
          plugin_reactions_details: percentage
